### ISSUE TITLE
Complete the adoption process with the Foundation.

### ISSUE THREAD

**Issue by cube2222** [opentffoundation/roadmap#1]

**Comment by nemobis** [comment]
For context 

> We completed all documents required for OpenTF to become part of the Linux Foundation with the end goal of having OpenTF as part of the Cloud Native Computing Foundation.

https://opentf.org/announcement

Before it's too late, it might also be a good idea to call this just OpenTF (or OpenTF project), as it won't need to be its own separate legal entity/foundation.

**Comment by roni-frantchi** [comment]
@nemobis thanks - absolutely and we're already working on that too - possibly under a new name https://github.com/opentffoundation/opentf/issues/296
