### ISSUE TITLE
Publicly release 1.6.0-alpha

### ISSUE THREAD

**Issue by cube2222** [opentffoundation/roadmap#10]

**Comment by Tchoupinax** [comment]
Hey!

Great to see the first release of opentf becoming alive. I was looking for source code, opentf side. Did you already fork? When will it be available?

Thank you!

**Comment by cube2222** [comment]
Hey @Tchoupinax!

If you haven't seen it yet, take a look at our latest announcement: https://opentf.org/announcement

However, to answer your questions directly.

> Did you already fork?

Yes, a while ago already.

> When will it be available?

No hard date yet, but very soon. Most likely days from now.

**Comment by roni-frantchi** [comment]
This is now tracked as milestone [here](https://github.com/opentffoundation/opentf/milestone/1)
