### ISSUE TITLE
Future: Be a part of CNCF ecosystem

### ISSUE THREAD

**Issue by jkroepke** [opentffoundation/roadmap#22]
Dear OpenTF Foundation.

I would like to ask if its on the Roadmap to become a [CNCF](https://landscape.cncf.io/) project in the future. From my point of view, we miss such an project like OpenTF on the CNCF catalog. 

I think, become part of the CNCF eco system could be a real benefit for the worlds IT ecosystem and would fully establish the trust and would be a huge benefit of other existing projects.

**Comment by roni-frantchi** [comment]
Hey @jkroepke thanks for the issue.  
Doing some cleanup roadmap repo as we're moving to manage our issues and roadmap onto [github.com/opentffoundation/opentf](github.com/opentffoundation/opentf) so I will now be closing this issue before marking this repo as archived, I wanted to comment on CNCF - we _are_ in the process of getting there, and I'm sure the there'd be updates coming soon 😃 

You're welcome to resubmit this issue on the main repo / start a discussion / check us out on Slack of course! ❤️
