### ISSUE TITLE
Adopt a code of conduct

### ISSUE THREAD

**Issue by dhasenan** [opentffoundation/roadmap#26]
You're going to end up with contributors who are bigoted or otherwise going to make trouble for others. If you don't have a strategy in place to deal with them from the start, the troublemakers have a significant advantage. It's better to settle on a code of conduct (and moderation procedures) before problems come up rather than after troublemakers drive other contributors out.

**Comment by cube2222** [comment]
Hey @dhasenan! We've adopted the CNCF code of conduct.
