### ISSUE TITLE
Design new contribution guidelines.

### ISSUE THREAD

**Issue by cube2222** [opentffoundation/roadmap#4]

**Comment by Fraetor** [comment]
Given it was the cause of the issue, a CLA should probably be avoided. To fulfil the role of ensurung contributors have the appropriate rights to their submissions you could either adopt something like the [Developer Certificate of Origin](https://drewdevault.com/2021/04/12/DCO.html), or instead just rely on the similar clause in [section D.6 of GitHub's ToS](https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#6-contributions-under-repository-license).

**Comment by cube2222** [comment]
@Fraetor Fair point! We'll be working with the foundation to set up the submission process. We'd definitely prefer having the process as minimal as possible.

**Comment by cube2222** [comment]
We've ended up using the [Developer Certificate of Origin](https://developercertificate.org).
