### ISSUE TITLE
Build a new release process, including package distribution as a binary, Docker image, Homebrew, Debian and rpm packages.

### ISSUE THREAD

**Issue by cube2222** [opentffoundation/roadmap#8]

**Comment by rjudin** [comment]
I can help with this

**Comment by ilmax** [comment]
Can I also suggest to add Winget to the list above?

**Comment by Kieranties** [comment]
I can help in support Winget if needed

**Comment by mihajlovics** [comment]
I'd like to see us adding support for MacPorts too, if that's a relatively quick thing to do.

**Comment by Xanazf** [comment]
aur package please

**Comment by mik3h0** [comment]
There are also a few projects such as tfenv and flora that are handy for those needing to have multiple versions available.

I think contributing to those so opentf can be made available with those tools would really help folks migrate.

**Comment by rjudin** [comment]
Plus tfswitch than is handy for version changing)works for all platforms)

**Comment by joelio** [comment]
Echoing other sentiments here, any idea on eta?

**Comment by roni-frantchi** [comment]
Thanks everyone for commenting!  
Now that OpenTF's repo is available we'll be moving issue tracking there.  

You can resume this discussion on this issue: https://github.com/opentffoundation/opentf/issues/160
